domain: my_domain
descriptors:
- key: generic_key
  value: instance_1
  descriptors:
    - key: header_match
      value: get_request
      rate_limit:
        unit: MINUTE
        requests_per_unit: 5