apiVersion: extensions.istio.io/v1alpha1
kind: WasmPlugin
metadata:
  name: wasm-example
  namespace: default
spec:
  selector:
    matchLabels:
      app: httpbin
  url: oci://0xmantis/wasm:v1
  pluginConfig:
    header_1: first_header
    header_2: second_header